# Generated by Django 5.2.1 on 2025-06-22 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_identidades', '0003_respuestasolicitud'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='tipo',
            field=models.CharField(choices=[('creacion_usuario', 'Autoregistro'), ('solicitar_usuario', 'Solicitar usuario en IAM'), ('creacion_identidades', 'Formulario de gestion de identidades'), ('creacion_paz', 'Formulario de paz y salvo')], default='creacion_usuario', max_length=50, verbose_name='Tipo de formulario'),
        ),
    ]
